# Generated by Django 2.0.3 on 2019-04-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subscription_id',
            new_name='membership_type',
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='desc',
            field=models.CharField(default='30 day membership recurring', max_length=100),
        ),
    ]
