# Generated by Django 2.0.3 on 2019-04-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190402_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldgymproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='soldgymproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercartlog',
            name='product',
        ),
        migrations.RemoveField(
            model_name='usercartlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermembershiplog',
            name='membership_plan',
        ),
        migrations.RemoveField(
            model_name='usermembershiplog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrefund',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.DeleteModel(
            name='SoldGymProduct',
        ),
        migrations.DeleteModel(
            name='UserCartLog',
        ),
        migrations.DeleteModel(
            name='UserMembershipLog',
        ),
        migrations.DeleteModel(
            name='UserRefund',
        ),
    ]
