# Generated by Django 2.0.3 on 2019-04-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_usermembership_last_mem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_membership_id',
        ),
    ]
