# Generated by Django 2.0.3 on 2019-10-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_usercheckin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
